version: "3.9"

services:
  db:
    image: postgres:13.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./src/main/resources/scripts/setup_local_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"